In [1]:
%pwd

'/Users/ryandevera/data-science/umn_environments/Constrained-Deep-Learning-Survey/notebooks'

In [2]:
%cd ..

/Users/ryandevera/data-science/umn_environments/Constrained-Deep-Learning-Survey


/Users/ryandevera/.virtualenvs/cdl-survey/lib/python3.9/site-packages/IPython/core/magics/osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


In [3]:
import numpy as np
import pandas as pd

from cdlsurvey.data import get_data, discretize_continuous_columns, get_data()

In [4]:
# Define the columns that we want to use
# Categorical columns
CATEGORICAL_COLUMNS = [
    'workclass',
    'education',
    'marital_status',
    'occupation',
    'relationship',
    'race',
    'gender',
    'native_country',
]

# Continuous columns
CONTINUOUS_COLUMNS = [
    'age',
    'capital_gain',
    'capital_loss',
    'hours_per_week',
    'education_num',
]

# All columns
COLUMNS = [
    'age',
    'workclass',
    'fnlwgt',
    'education',
    'education_num',
    'marital_status',
    'occupation',
    'relationship',
    'race',
    'gender',
    'capital_gain',
    'capital_loss',
    'hours_per_week',
    'native_country',
    'income_bracket',
]

# label column
LABEL_COLUMN = 'label'

In [8]:
train_filename = 'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data'  # noqa
test_filename = 'https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test'  # noqa

# Get the train and test data
train_df = pd.read_csv(train_filename, names=COLUMNS, skipinitialspace=True)
test_df = pd.read_csv(test_filename, names=COLUMNS, skipinitialspace=True, skiprows=1)

In [9]:
train_df['age'].unique(), test_df['age'].unique()

(array([39, 50, 38, 53, 28, 37, 49, 52, 31, 42, 30, 23, 32, 40, 34, 25, 43,
        54, 35, 59, 56, 19, 20, 45, 22, 48, 21, 24, 57, 44, 41, 29, 18, 47,
        46, 36, 79, 27, 67, 33, 76, 17, 55, 61, 70, 64, 71, 68, 66, 51, 58,
        26, 60, 90, 75, 65, 77, 62, 63, 80, 72, 74, 69, 73, 81, 78, 88, 82,
        83, 84, 85, 86, 87]),
 array([25, 38, 28, 44, 18, 34, 29, 63, 24, 55, 65, 36, 26, 58, 48, 43, 20,
        37, 40, 72, 45, 22, 23, 54, 32, 46, 56, 17, 39, 52, 21, 42, 33, 30,
        47, 41, 19, 69, 50, 31, 59, 49, 51, 27, 57, 61, 64, 79, 73, 53, 77,
        80, 62, 35, 68, 66, 75, 60, 67, 71, 70, 90, 81, 74, 78, 82, 83, 85,
        76, 84, 89, 88, 87]))

In [21]:
_, bins_quantized = pd.qcut(train_df['age'], 4, retbins=True, labels=False)

In [22]:
train_df.loc[pd.cut(train_df['age'], bins_quantized).isnull()]

age workclass  fnlwgt education  education_num marital_status  \
106     17         ?  304873      10th              6  Never-married   
209     17   Private   65368      11th              7  Never-married   
262     17   Private  245918      11th              7  Never-married   
271     17   Private  191260       9th              5  Never-married   
335     17   Private  270942   5th-6th              3  Never-married   
...    ...       ...     ...       ...            ...            ...   
31772   17         ?  256173      10th              6  Never-married   
31864   17   Private  214787      12th              8  Never-married   
31959   17   Private   24090   HS-grad              9  Never-married   
32282   17   Private  311907      11th              7  Never-married   
32447   17   Private  117798      10th              6  Never-married   

            occupation    relationship   race  gender  capital_gain  \
106                  ?       Own-child  White  Female         34095   
209              Sales       Own-child  White  Female             0   
262      Other-service       Own-child  White    Male             0   
271      Other-service       Own-child  White    Male          1055   
335      Other-service  Other-relative  White    Male             0   
...                ...             ...    ...     ...           ...   
31772                ?       Own-child  White  Female             0   
31864     Adm-clerical       Own-child  White  Female             0   
31959  Exec-managerial       Own-child  White  Female             0   
32282    Other-service       Own-child  White    Male             0   
32447    Other-service       Own-child  White    Male             0   

       capital_loss  hours_per_week native_country income_bracket  
106               0              32  United-States          <=50K  
209               0              12  United-States          <=50K  
262               0              12  United-States          <=50K  
271               0              24  United-States          <=50K  
335               0              48         Mexico          <=50K  
...             ...             ...            ...            ...  
31772             0              15  United-States          <=50K  
31864             0              25  United-States          <=50K  
31959             0              35  United-States          <=50K  
32282             0              25  United-States          <=50K  
32447             0              20  United-States          <=50K  

[395 rows x 15 columns]

In [25]:
pd.cut(train_df['age'], bins_quantized, labels=False, include_lowest=True).unique()

array([2, 3, 0, 1])

In [26]:
pd.cut(test_df['age'], bins_quantized, labels=False, include_lowest=True).unique()

array([0, 2, 1, 3])

In [ ]:
get_data